application: vumilog
version: 1
runtime: python27
threadsafe: true
api_version: 1

libraries:
- name: django
  version: "1.3"

handlers:
- url: /(.*\.(html|css|js|gif|jpg|png|ico|swf))
  static_files: static/\1
  upload: static/.*
  expiration: "1d"

- url: /task/.*
  script: main.app
  login: admin

- url: /.*
  script: main.app
