application: vumilog
version: 1
runtime: python27
threadsafe: true
api_version: 1

libraries:
- name: django
  version: "1.2"

builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: static
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt
- url: /lock\.png
  static_files: static/lock.png
  upload: static/lock\.png
- url: /tasks/.*
  script: tasks.application
  login: admin
- url: /.*
  script: main.application

inbound_services:
- xmpp_message

skip_files:
- ^bulkloader.*$
- ^\..*$
- ^.*\.pyc